- name: Transfer and execute a script.
  hosts: all
  tasks:
    - name: Copy and execute the script
      script: ../cosmos-setup.sh
      args:
        executable: /bin/bash -c "source ../cosmos-setup.sh"